// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devBlog.Data;

#nullable disable

namespace devBlog.Migrations
{
    [DbContext(typeof(devBlogContext))]
    [Migration("20240801080751_RemovedAuthorId")]
    partial class RemovedAuthorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("devBlog.Models.BlogPost", b =>
                {
                    b.Property<Guid>("BlogPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AuthorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("BlogPostID");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("devBlog.Models.BlogPostTag", b =>
                {
                    b.Property<Guid>("BlogPostID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("BlogPostTag");
                });

            modelBuilder.Entity("devBlog.Models.Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("TagID");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            TagID = new Guid("67f3804b-2e4c-4d4c-bc65-2e68a6d59fd4"),
                            Name = "Development"
                        },
                        new
                        {
                            TagID = new Guid("256a4262-6e8c-48bf-b417-4aa0860c9488"),
                            Name = "Web Development"
                        },
                        new
                        {
                            TagID = new Guid("ea87cc48-ca65-496f-b0e2-d244589fda1b"),
                            Name = "CSS"
                        },
                        new
                        {
                            TagID = new Guid("47400c8d-4c7e-4df3-ba1d-53b563670a3b"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            TagID = new Guid("26f0f375-680e-4a26-88c6-7b1696d2b7a6"),
                            Name = "Angular"
                        },
                        new
                        {
                            TagID = new Guid("47683a36-e952-4a75-90dc-f208f6c5cb7c"),
                            Name = "PHP"
                        },
                        new
                        {
                            TagID = new Guid("342d319f-5007-454c-b745-edc991a15dbd"),
                            Name = "HTML"
                        },
                        new
                        {
                            TagID = new Guid("d596f6a0-a3f3-4cce-9492-a0386306d39f"),
                            Name = "React"
                        },
                        new
                        {
                            TagID = new Guid("ed227003-fc98-4683-becc-5719b4174f30"),
                            Name = "Data Science"
                        },
                        new
                        {
                            TagID = new Guid("443106b3-7201-4234-982e-b1b5ba940e5d"),
                            Name = "Mobile Development"
                        },
                        new
                        {
                            TagID = new Guid("3d54b292-f4ae-4c7b-a2c5-cdd474dc0be0"),
                            Name = "Programming Language"
                        },
                        new
                        {
                            TagID = new Guid("1abcf16d-6e29-4362-a393-235ac76a6bd6"),
                            Name = "Software Testing"
                        },
                        new
                        {
                            TagID = new Guid("b8455130-b325-4656-80a6-5be15c13d74e"),
                            Name = "Software Engineering"
                        },
                        new
                        {
                            TagID = new Guid("f56bb2e2-f338-4111-88ef-4ceda922711e"),
                            Name = "Software Development Tools"
                        },
                        new
                        {
                            TagID = new Guid("4dee430c-a677-4106-a783-1e75f5677c31"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            TagID = new Guid("386b6650-79a7-44ce-a9b8-74825734500d"),
                            Name = "Network Security"
                        },
                        new
                        {
                            TagID = new Guid("a9e689a4-975c-413f-84c2-dd0a25ccb6af"),
                            Name = "Application Security"
                        },
                        new
                        {
                            TagID = new Guid("87181401-d0df-4e62-a701-4dcd44ed03ad"),
                            Name = "Data Privacy"
                        },
                        new
                        {
                            TagID = new Guid("b87a8480-cc91-4e2d-8ff9-9f4a77512289"),
                            Name = "Incident Response"
                        },
                        new
                        {
                            TagID = new Guid("13086d29-1cea-4d01-8b4e-9ab46c3bc4cf"),
                            Name = "Security Tools"
                        },
                        new
                        {
                            TagID = new Guid("6f10ed9d-42df-4398-ad13-a29acdb7fc01"),
                            Name = "AI / ML"
                        },
                        new
                        {
                            TagID = new Guid("9b05aeea-cc50-49f6-9daf-1b883a32e9df"),
                            Name = "Machine Learning Algorithms"
                        },
                        new
                        {
                            TagID = new Guid("59b44982-8a8d-43fa-a171-ae64bcafd1ae"),
                            Name = "Deep Learning"
                        },
                        new
                        {
                            TagID = new Guid("03319be9-e0c3-4e0f-8694-b06269b2a3bd"),
                            Name = "AI Applications"
                        },
                        new
                        {
                            TagID = new Guid("8c937d06-3f61-43e0-8f65-3b283f430cef"),
                            Name = "Ethics in AI"
                        },
                        new
                        {
                            TagID = new Guid("c533d844-a66f-4a4f-97d8-d7275b5198dc"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            TagID = new Guid("93d5f149-a985-42de-8121-a78953e962b6"),
                            Name = "Tech Industry News"
                        });
                });

            modelBuilder.Entity("devBlog.Models.BlogPostTag", b =>
                {
                    b.HasOne("devBlog.Models.BlogPost", "BlogPost")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("BlogPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("devBlog.Models.Tag", "Tag")
                        .WithMany("BlogPostTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("devBlog.Models.BlogPost", b =>
                {
                    b.Navigation("BlogPostTags");
                });

            modelBuilder.Entity("devBlog.Models.Tag", b =>
                {
                    b.Navigation("BlogPostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
